CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    name          VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    image_path  VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at  TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_items_owner ON items (owner_id) WHERE deleted_at IS NULL;

CREATE TABLE votings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at  TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_votings_owner ON votings (owner_id) WHERE deleted_at IS NULL;

CREATE TABLE voting_items (
    voting_id BIGINT NOT NULL REFERENCES votings (id) ON DELETE RESTRICT,
    item_id   BIGINT NOT NULL REFERENCES items (id) ON DELETE RESTRICT,
    position  INTEGER NOT NULL,
    PRIMARY KEY (voting_id, item_id)
);

CREATE TABLE voting_points (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    code        VARCHAR(8) NOT NULL UNIQUE,
    voting_id   BIGINT REFERENCES votings (id) ON DELETE RESTRICT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at  TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_voting_points_owner ON voting_points (owner_id) WHERE deleted_at IS NULL;

CREATE TABLE voting_instances (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voting_point_id BIGINT NOT NULL REFERENCES voting_points (id) ON DELETE RESTRICT,
    voting_id       BIGINT NOT NULL REFERENCES votings (id) ON DELETE RESTRICT,
    status          VARCHAR(20) NOT NULL,
    started_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at        TIMESTAMP WITH TIME ZONE
);
-- Solo una instancia activa por punto de votacion
CREATE UNIQUE INDEX uq_active_instance_per_point ON voting_instances (voting_point_id) WHERE status = 'ACTIVE';
CREATE INDEX idx_instances_point ON voting_instances (voting_point_id);

CREATE TABLE votes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id BIGINT NOT NULL REFERENCES voting_instances (id) ON DELETE RESTRICT,
    item_id     BIGINT NOT NULL REFERENCES items (id) ON DELETE RESTRICT,
    voter_token VARCHAR(64) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_vote_per_voter UNIQUE (instance_id, voter_token)
);
CREATE INDEX idx_votes_instance_item ON votes (instance_id, item_id);
