-- Tipos de votacion (SINGLE, LIMITED, RANKING) y papeletas con varias selecciones

ALTER TABLE votings ADD COLUMN type VARCHAR(20) NOT NULL DEFAULT 'SINGLE';
ALTER TABLE votings ADD COLUMN max_selections INTEGER;

-- Una papeleta por dispositivo e instancia
CREATE TABLE ballots (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id BIGINT NOT NULL REFERENCES voting_instances (id) ON DELETE RESTRICT,
    voter_token VARCHAR(64) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_ballot_per_voter UNIQUE (instance_id, voter_token)
);
CREATE INDEX idx_ballots_instance ON ballots (instance_id);

-- Migrar los votos existentes: una papeleta por (instancia, votante)
INSERT INTO ballots (instance_id, voter_token, created_at)
    SELECT instance_id, voter_token, MIN(created_at)
    FROM votes
    GROUP BY instance_id, voter_token;

ALTER TABLE votes ADD COLUMN ballot_id BIGINT REFERENCES ballots (id) ON DELETE RESTRICT;
UPDATE votes v
    SET ballot_id = b.id
    FROM ballots b
    WHERE b.instance_id = v.instance_id AND b.voter_token = v.voter_token;
ALTER TABLE votes ALTER COLUMN ballot_id SET NOT NULL;

-- Posicion en la papeleta (1 = mejor) solo en votaciones de tipo RANKING
ALTER TABLE votes ADD COLUMN rank_position INTEGER;

ALTER TABLE votes DROP CONSTRAINT uq_vote_per_voter;
ALTER TABLE votes DROP COLUMN voter_token;
ALTER TABLE votes ADD CONSTRAINT uq_vote_item_per_ballot UNIQUE (ballot_id, item_id);
CREATE INDEX idx_votes_ballot ON votes (ballot_id);
