import {
  ArrowLeft,
  Ban,
  ChartBar,
  ChevronDown,
  ChevronUp,
  Check,
  CircleAlert,
  CircleCheck,
  CircleDot,
  Clock,
  Copy,
  Download,
  Filter,
  History,
  Image,
  ImageOff,
  Inbox,
  Info,
  LayoutDashboard,
  Link,
  ListChecks,
  ListOrdered,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Package,
  Pencil,
  Play,
  Plus,
  QrCode,
  Radio,
  Square,
  Trash2,
  Upload,
  User,
  Vote,
  X,
} from 'lucide-angular';

/** Subconjunto de iconos usados en la aplicación. */
export const ICONS = {
  back: ArrowLeft,
  ban: Ban,
  stats: ChartBar,
  check: Check,
  up: ChevronUp,
  down: ChevronDown,
  alert: CircleAlert,
  success: CircleCheck,
  typeSingle: CircleDot,
  clock: Clock,
  copy: Copy,
  download: Download,
  filter: Filter,
  history: History,
  image: Image,
  imageOff: ImageOff,
  empty: Inbox,
  info: Info,
  dashboard: LayoutDashboard,
  link: Link,
  typeLimited: ListChecks,
  typeRanking: ListOrdered,
  loader: LoaderCircle,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  point: MapPin,
  menu: Menu,
  item: Package,
  edit: Pencil,
  play: Play,
  plus: Plus,
  qr: QrCode,
  live: Radio,
  stop: Square,
  trash: Trash2,
  upload: Upload,
  user: User,
  voting: Vote,
  close: X,
} as const;
